AWSTemplateFormatVersion: '2010-09-09'
Description: Base stack to create EKS cluster and nodes

Parameters:

  # Make sure that config file for your region exists and is publicly accessible
  BuildScriptsLocation:
    Description: Source folder in S3 bucket hosting all files
    Type: String
    # dont use a trailing '/' its in the buildspec 
    Default: https://anz-container-day.s3-ap-southeast-2.amazonaws.com/EE/eks_codebuild_cfn/source

  Cloud9IDEInstanceType:
    Description: The type of instance to connect to the environment
    Type: String
    Default: t3.large


Resources:  
  Cloud9IDE:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      Name : EKSLabIDE
      AutomaticStopTimeMinutes: 900
      Description: Use this to work with EKS Labs
      InstanceType: !Ref Cloud9IDEInstanceType
      OwnerArn :  !Sub arn:aws:sts::${AWS::AccountId}:assumed-role/TeamRole/MasterKey
      Repositories:
        - RepositoryUrl: https://github.com/anz-containers/eks-init-scripts
          PathComponent: init_scripts

  Cloud9IDEInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - TeamRole

  BuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn: [Cloud9IDE, Cloud9IDEInstanceProfile]
    Properties:
      Name: !Sub CodeBuild-${AWS::StackName}
      Description: A description about my project
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/TeamRole
      Artifacts:
        Type: NO_ARTIFACTS
      LogsConfig:
        CloudWatchLogs:
          Status:  ENABLED
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        EnvironmentVariables:
          - Name: CFN_RESPONSE_URL
            Value: !Ref WaitForStackCreationHandle
          - Name: BUILDSCRIPTSLOCATION
            Value: !Ref BuildScriptsLocation
          - Name: CLOUD9_INSTANCE_PROFILE_NAME
            Value: !Ref Cloud9IDEInstanceProfile
          - Name: CLOUD9_ENVIRONMENT_ID
            Value: !Ref Cloud9IDE
      Source:
        Type: NO_SOURCE
        BuildSpec: 
          !Sub |
            version: 0.2
            phases:
              install:
                runtime-versions:
                  python: 3.7
                commands:
                  - echo ">>> installed python 3.7"
              pre_build:
                commands:
                  - echo ">>> get config from s3"
                  - curl $BUILDSCRIPTSLOCATION/cluster-config-$AWS_DEFAULT_REGION.yaml --output cluster-config.yaml
                  - echo ">>> install awscli "
                  - pip3 install --upgrade --user awscli
                  - echo ">>> install kubectl"
                  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
                  - chmod +x ./kubectl 
                  - curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
                  - mv -v /tmp/eksctl /usr/local/bin
                  - eksctl version
                  - export PATH=$PWD/:$PATH
              build:
                commands:
                  - echo ">>> find instance using environment Id= $CLOUD9_ENVIRONMENT_ID"
                  - CLOUD9_INSTANCE_ID=$(aws ec2 describe-instances --filter Name=tag:aws:cloud9:environment,Values=$CLOUD9_ENVIRONMENT_ID --query Reservations[0].Instances[0].InstanceId --output text)
                  - echo ">>> cloud9 instance id= $CLOUD9_INSTANCE_ID"
                  - echo ">>> assign profile $CLOUD9_INSTANCE_PROFILE_NAME to instance $CLOUD9_INSTANCE_ID"
                  - aws ec2 associate-iam-instance-profile --instance-id $CLOUD9_INSTANCE_ID --iam-instance-profile Name=$CLOUD9_INSTANCE_PROFILE_NAME
                  - eksctl create cluster -f cluster-config.yaml
              post_build:
                commands: 
                  # CODEBUILD_BUILD_SUCCEEDING = 1 Set to 0 if the build is failing, or 1 if the build is succeeding.
                  - echo ">>> build status $CODEBUILD_BUILD_SUCCEEDING "
                  - |
                    if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq "1" ]
                    then
                      curl -X PUT -H 'Content-Type:' --data-binary '{"Status" : "SUCCESS","Reason" : "Creation Complete", "UniqueId" : "$CODEBUILD_BUILD_ID","Data" : "Creation complete"}' $CFN_RESPONSE_URL
                    else
                      curl -X PUT -H 'Content-Type:' --data-binary '{"Status" : "FAILURE","Reason" : "Creation Failed", "UniqueId" : "$CODEBUILD_BUILD_ID","Data" : "See Codebuild logs for details. $CODEBUILD_LOG_PATH"}' $CFN_RESPONSE_URL
                    fi
      TimeoutInMinutes: 60


  WaitForStackCreationHandle: 
    Type: AWS::CloudFormation::WaitConditionHandle

  WaitCondition: 
    Type: AWS::CloudFormation::WaitCondition
    # dont start till we create a lambda function
    DependsOn: [CustomTriggerBuild]
    Properties: 
      Handle: !Ref WaitForStackCreationHandle
      # wait for 55 minutes before giving up
      Timeout: 3300
      # success or failure signal count 
      Count: 1

  CustomTriggerBuild: 
    Type: Custom::ManageCloud9IDEIamRole
    DependsOn: BuildProject
    Properties: 
      ServiceToken: !GetAtt TriggerBuildLambda.Arn
      CodebuildProjectName: !Ref BuildProject

  TriggerBuildLambdaIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: !Sub IAMPolicy-${AWS::StackName}
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                    - codebuild:*
                Resource: !GetAtt BuildProject.Arn

  TriggerBuildLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: function to retrive User info
      Handler: index.handler
      Role: !GetAtt TriggerBuildLambdaIamRole.Arn
      Runtime: python3.7
      Code:
        ZipFile: |
          import boto3
          import logging
          import sys
          import json
          import urllib3

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          http = urllib3.PoolManager()

          # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html
          def handler(event, context):
              logger.info('Incoming Event: {0}'.format(event))
              response = {}
              response['PhysicalResourceId'] = 'hardcodedphyscialid'
              response['StackId'] = event['StackId']
              response['RequestId'] = event['RequestId']    
              response['LogicalResourceId'] = event['LogicalResourceId']
              cfn_response_url = event['ResponseURL']

              if event['RequestType'] == 'Delete':
                  # return 
                  logger.info('Nothing to do. Request Type : {0}'.format(event['RequestType']))
                  response['Status'] = 'SUCCESS'

              elif event['RequestType'] == 'Create' or event['RequestType'] == 'Update':

                try:
                  codebuild_client = boto3.client('codebuild')
                  codebuild_client.start_build(projectName=event['ResourceProperties']['CodebuildProjectName'])
                  response['Status'] = 'SUCCESS'

                except:
                  logging.error('Error: {0}'.format(sys.exc_info() ))
                  response['Status'] = 'FAILED'

              http.request('PUT', cfn_response_url, body=json.dumps(response).encode('utf-8'), headers={'Content-Type': 'application/json'})

              return 'Done'

Outputs:
  Cloud9IDEId:
    Description: ID of the development environment
    Value: !Ref Cloud9IDE

  Cloud9IDEArn:
    Description: ARN of the development environment
    Value: !GetAtt Cloud9IDE.Arn

  Cloud9IDEName:
    Description: The name of the environment
    Value: !GetAtt Cloud9IDE.Name

  Cloud9IDEInstanceProfileName:
    Description: Instance profile to be assigned to Cloud9 IDE 
    Value: !Ref Cloud9IDEInstanceProfile
