apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

#Only use these availability zones
availabilityZones:
  - us-east-2a
  - us-east-2b
  - us-east-2c

metadata:
  name: EKS-Lab
  region: us-east-2
  version: "1.14"

cloudWatch:
    clusterLogging:
        enableTypes: ["*"]

nodeGroups:
  - name: ng
    instanceType: m5.xlarge
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true