apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

#Only use these availability zones
availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c

metadata:
  name: EKS-Lab
  region: us-east-1
  version: "1.14"

cloudWatch:
    clusterLogging:
        enableTypes: ["*"]

nodeGroups:
  - name: ng
    instanceType: m5.xlarge
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
fargateProfiles:
  - name: dev-test
    selectors:
      - namespace: default
        labels:
          scheduler: fargate

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: s3-dynamo-read-access
        namespace: backend
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess